[package]
name = "yalp"
version = "0.1.0"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[dependencies]
rustyline = "*"
custom_derive = "*"
enum_derive = "*"
clippy = {version = "*", optional = true}

[features]
default = []

[lib]
name = "yalp"

[[bin]]
name = "yalp"

[profile.release]
debug = true
lto = false

